# Generated by Django 4.2.30 on 2026-07-01 10:40

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=12, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_email', models.EmailField(max_length=254)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('canceled', 'Storniert')], default='active', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unbezahlt'), ('paid', 'Bezahlt'), ('refunded', 'Rueckerstattet')], default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('offer_type', models.CharField(choices=[('flight', 'Flug'), ('hotel', 'Hotel'), ('car', 'Mietwagen')], max_length=20)),
                ('location', models.CharField(max_length=120)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('4.0'), max_digits=3)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('season_factor', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('demand_factor', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('availability_factor', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('available_units', models.PositiveIntegerField(default=10)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('canceled_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='api.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='api.offer'),
        ),
    ]
